import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const [landing, readme, mainRuntime, parserRuntime] = await Promise.all([
  readFile(resolve(root, "site/index.html"), "utf8"),
  readFile(resolve(root, "README.md"), "utf8"),
  readFile(resolve(root, "site/src/main.ts"), "utf8"),
  readFile(resolve(root, "site/src/demo.ts"), "utf8")
]);
const runtime = `${mainRuntime}\n${parserRuntime}`;

function plain(value) {
  return value
    .replace(/<svg\b[\s\S]*?<\/svg>/gi, "")
    .replace(/<[^>]+>/g, " ")
    .replace(/&(?:rarr|#8594);/g, "→")
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&#39;|&apos;/g, "'")
    .replace(/\s+/g, " ")
    .trim();
}

function words(value) {
  return value.split(/\s+/).filter((token) => /[\p{L}\p{N}]/u.test(token)).length;
}

function rows(values) {
  return [...new Set(values.map((value) => value.trim()).filter(Boolean))]
    .map((value) => `| ${words(value)} | ${value.replace(/\|/g, "\\|")} |`)
    .join("\n");
}

function elements(html, tags) {
  const matcher = new RegExp(`<(${tags.join("|")})\\b[^>]*>([\\s\\S]*?)<\\/\\1>`, "gi");
  return [...html.matchAll(matcher)].map((match) => plain(match[2])).filter(Boolean);
}

function sentences(values) {
  return values.flatMap((value) => value.split(/(?<=[.!?])\s+(?=[A-Z`])/).map((sentence) => sentence.trim()).filter(Boolean));
}

const landingSentences = sentences(elements(landing, ["p"]));
const landingFragments = elements(landing, ["h1", "h2", "h3", "button", "a", "legend", "label", "strong", "span"]);
const dynamic = [
  ["3 sidecars parsed locally.", "sidecars parsed locally."],
  ["Choose editing steps, then search.", "Choose editing steps, then search."],
  ["2 of 3 sidecars match all selected operations.", "sidecars match ${mode} selected operations."],
  ["No sidecar content yet.", "No sidecar content yet."],
  ["Paste a sidecar or choose files.", "Paste a sidecar or choose files."],
  ["No matching trails.", "No matching trails."],
  ["Try “Any selected” or choose fewer operations.", "Try “Any selected” or choose fewer operations."],
  ["Could not parse [name].", "Could not parse ${name}."],
  ["Check that its XML, DOP, or PP3 data is complete.", "data is complete."],
  ["This DOP does not identify DxO PhotoLab.", "This DOP does not identify DxO PhotoLab."],
  ["No DxO correction states were found.", "No DxO correction states were found."],
  ["Command copied.", "Command copied"],
  ["Could not copy.", "Could not copy."],
  ["Select the command manually.", "Select the command manually."]
];
for (const [, anchor] of dynamic) {
  if (!runtime.includes(anchor)) throw new Error(`Dynamic copy audit anchor is missing: ${anchor}`);
}

const markdownLines = readme
  .replace(/```[\s\S]*?```/g, "")
  .replace(/\[([^\]]+)]\([^\)]+\)/g, "$1")
  .replace(/[`*_]/g, "")
  .split("\n");
const markdownBlocks = [];
let paragraph = [];
const flushParagraph = () => {
  if (paragraph.length) markdownBlocks.push(paragraph.join(" "));
  paragraph = [];
};
for (const line of markdownLines) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith("#")) {
    flushParagraph();
  } else if (trimmed.startsWith("- ")) {
    flushParagraph();
    markdownBlocks.push(trimmed.slice(2));
  } else {
    paragraph.push(trimmed);
  }
}
flushParagraph();
const readmeSentences = sentences(markdownBlocks);
const readmeHeadings = [...readme.matchAll(/^#{1,6}\s+(.+)$/gm)].map((match) => match[1].trim());

const longest = [...landingSentences, ...dynamic.map(([value]) => value), ...readmeSentences]
  .map((value) => ({ value, count: words(value) }))
  .sort((a, b) => b.count - a.count)[0];
if (longest.count > 22) throw new Error(`Copy exceeds 22 words (${longest.count}): ${longest.value}`);
const banned = /\b(?:leverage|seamless|effortless|robust|powerful|intuitive|reimagine|supercharge|delightful|journey|ecosystem|AI-powered)\b/i;
for (const value of [...landingSentences, ...landingFragments, ...dynamic.map(([copy]) => copy), ...readmeSentences]) {
  if (banned.test(value)) throw new Error(`Banned wording in copy: ${value}`);
}

const output = `# Copy audit — generated 30 August 2026

Generated by \`npm run copy:audit\`. The tokenizer splits on whitespace and
counts tokens containing a letter or number. Hyphenated terms, paths, flags,
and versions count once. \`npm run copy:audit:check\` fails when this file
differs or a sentence exceeds 22 words.

## Landing-page sentences

| Words | Exact sentence |
| ---: | --- |
${rows(landingSentences)}

## Dynamic browser sentences

| Words | Exact rendered example |
| ---: | --- |
${rows(dynamic.map(([value]) => value))}

## Landing headings, controls, and copy fragments

| Words | Exact text |
| ---: | --- |
${rows(landingFragments)}

## README sentences

| Words | Exact sentence |
| ---: | --- |
${rows(readmeSentences)}

README headings: ${readmeHeadings.map((heading) => `**${heading}**`).join(", ")}.

## Terminology

| Concept | One term |
| --- | --- |
| User-visible edit | editing step |
| Stored editor field | operation |
| Supplemental editor file | sidecar |
| Translation into shared names | normalise operation names |
`;

const destination = resolve(root, ".factory/copy-audit.md");
if (process.argv.includes("--check")) {
  const current = await readFile(destination, "utf8");
  if (current !== output) throw new Error(".factory/copy-audit.md is stale; run npm run copy:audit");
  console.log(`Copy audit is current; longest sentence has ${longest.count} words`);
} else {
  await writeFile(destination, output);
  console.log(`Wrote .factory/copy-audit.md; longest sentence has ${longest.count} words`);
}
